---
title: "Assignment 8.1"
geometry: paperheight=18in,paperwidth=9in,margin=1in
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
rm(list=ls())
```

<!-- # Libraries and other setup -->
```{r results="hide", message=FALSE, warning=FALSE}
# library(broom)
library(cvar)
# library(data.table)
# library(e1071)
library(kableExtra)
# library(gdata)
# library(ggpubr)
# library(grid)
library(gridExtra)
# library(gtable)
library(ggpubr)
library(gridGraphics)
library(lubridate)
library(magrittr)
library(readr)
# library(readxl)
# library(reshape2)
library(tidyverse)
library(tseries)
library(zoo)

setwd("D:/Documents/MGT 6090/Assignment 8")
```

<!-- # Saved env variables -->
```{r eval=TRUE}
# contains compustat and crsp_msf data
# load("base.RData")
load("out.RData")
```

```{r eval=TRUE, results="asis"}
for (i in 1:length(companies)) {
# for (i in 1:3) {
  company <- companies[i]
  out_betas %>%
    filter(PERMNO == company) %>%
    knitr::kable(digits = 6, format.args = list(scientific = FALSE)) %>%
    kable_styling(font_size = 6, latex_options = c("hold_position")) %>%
    print()
  cat('\\pagebreak')
}
```


